### ISSUE TITLE
Undefined function 'eregi_replace'

### ISSUE THREAD

**Issue by David-Baron** [fbouffanet/assoactes#4]
In v4/Administration/chargement.php

All eregi_replace(), ereg(), split()

This function was DEPRECATED in PHP 5.3.0, and REMOVED in PHP 7.0.0. 
See [php doc](http://php.adamharvey.name/manual/en/function.eregi-replace.php)

**Comment by fbouffanet** [comment]
Hello David,

Many thanks for the notices.
I have begun to fix the issues.

Can you get the latest release ?

Best Regards

    Fabrice

**Comment by fbouffanet** [comment]
Replaced with pre_replace. Actually, this code is used for Nimègue V2. We don't use it anymore
