### ISSUE TITLE
Install or parameter fail

### ISSUE THREAD

**Issue by David-Baron** [fbouffanet/assoactes#5]
Impossible de se connecter avec des installations classiques.
Testé sous serveur interne et wamp.
php 7.1
mariaDb 10.4

Comme décrit dans le wiki.

Page de connexion, l' indenti/mdp return erreur.

**Comment by fbouffanet** [comment]
Bonsoir,

Le programme passe sous Xamp en:
- PHP 7.4.16
- MariaDB 10.4.18

Utilisez-vous 1 comme identifiant ?
Je vais relancer l'installation pour voir s'il y a une régression mais pas avant dimanche.

Il serait plus simple d'échanger en direct.

Cordialement

**Comment by David-Baron** [comment]
Ah! Pour moi un identifient est un username/pseudo/email .....

**Comment by fbouffanet** [comment]
L'identifiant est 1 uniquement au démarrage de l'installation. Le programme a été conçu à l'origine pour une association dont l'identifiant était le numéro d'adhérent. Vous pouvez le changer par la suite par un username/pseudo.

Pouvez-vous créer le répertoire logs et poursuivre ? je rajouterai le dossier dans l'installation plus tard

Faites-vous partie d'une association généalogique ?

**Comment by David-Baron** [comment]
Je ne fais pas parti d'association mais j'ai eu à les consultées. Je sais que le plupart sont encore sous actes qui est complètement obsolète voir dangereux pour ceux qui sont en auto hébergé et bientôt (si ce n'ai déjà fait) hors service pour les autres. J'ai commencer a refaire une app en partant de actes lorsque je suis tombé sur la votre. J'ai donc souhaiter l'essayer.

**Comment by David-Baron** [comment]
Je ne sais pas si c'est a moi de close les issues ou si c'est vous qui le faites.

**Comment by fbouffanet** [comment]
J'ai fermé les autres problèmes. je fermerai celui-ci lorsque j'aurai ajouté les logs

C'est une très bonne idée de refaire un programme de diffusion de relevés plus au norme. Moi-même, j'ai conscience que que mon programme devrait être ré-écrit avec un framework plus récent mais je n'ai pas non plus le temps ni les connaissances.

Il y a aussi des besoins qui ne sont pas compris dans actes et qu'il serait intéressant d'avoir:
- réelle recherche phonétique dans les noms et prénoms
- recherche géographique
- recherche par couple en une seule fois
- interfaçage avec Généabank.

Si vous voulez échanger sur le sujet ou vous inspirez de ce que j'ai fait, je suis dispo

**Comment by David-Baron** [comment]
Je suis prêt a participer si vous souhaiter. davidbaron17 at yahoo dot fr. Veuillez supprimer ce message après avoir noté l’e-mail.

**Comment by fbouffanet** [comment]
Le dossier logs est maintenant créé lors de l'installation. J'ai aussi supprimé le fichiers obsolètes du dossier error ainsi que d'autres résidus
