### ISSUE TITLE
Table stats_gbk inexistante

### ISSUE THREAD

**Issue by David-Baron** [fbouffanet/assoactes#7]
Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 La table 'assoactes.stats_gbk' n'existe pas 

Appelée par 
menu / stats /export historique
Fichier concerné
stats/exportHisto.php

5 requêtes concernées
$st_requete_gbk_tot = "SELECT year(date_demande),month(date_demande),count(*)as nombre FROM stats_gbk  GROUP BY year(date_demande),month(date_demande) ORDER BY year(date_demande) asc";
$a_gbk_tot = $connexionBD->liste_valeur_par_doubles_clefs($st_requete_gbk_tot);

$st_requete_gbk_cm = "SELECT year(date_demande),month(date_demande),count(*)as nombre FROM stats_gbk where idf_type_acte=".IDF_CM." GROUP BY year(date_demande),month(date_demande) ORDER BY year(date_demande) asc";
$a_gbk_cm = $connexionBD->liste_valeur_par_doubles_clefs($st_requete_gbk_cm);

$st_requete_gbk_mar = "SELECT year(date_demande),month(date_demande),count(*)as nombre FROM stats_gbk where idf_type_acte=".IDF_MARIAGE." GROUP BY year(date_demande),month(date_demande) ORDER BY year(date_demande) asc";
$a_gbk_mar = $connexionBD->liste_valeur_par_doubles_clefs($st_requete_gbk_mar);

$st_requete_gbk_nai = "SELECT year(date_demande),month(date_demande),count(*)as nombre FROM stats_gbk where idf_type_acte=".IDF_NAISSANCE." GROUP BY year(date_demande),month(date_demande) ORDER BY year(date_demande) asc";
$a_gbk_nai = $connexionBD->liste_valeur_par_doubles_clefs($st_requete_gbk_nai);

$st_requete_gbk_dec = "SELECT year(date_demande),month(date_demande),count(*)as nombre FROM stats_gbk where idf_type_acte=".IDF_DECES." GROUP BY year(date_demande),month(date_demande) ORDER BY year(date_demande) asc";
$a_gbk_dec = $connexionBD->liste_valeur_par_doubles_clefs($st_requete_gbk_dec);

Fichier et lien obsolète ou table manquante?

**Comment by fbouffanet** [comment]
Il s'agit des statistiques de connexion à Généabank. Si vous voulons un module indépendant de Généabank, cette partie doit être supprimée (ou déplacée dans un autre script) de ce script

**Comment by fbouffanet** [comment]
Bonjour David,

La génération des Statistiques généabank est maintenant faite uniquement si un compte généabank existe (s'il est vide, l'outil n'est pas censé utiliser Généabank)

Cdlt
